---
after_failure:
  - perl ./maint-travis-ci/report_fail_ctx.pl
before_install:
  - perlbrew list
  - time git clone --depth 10 https://github.com/kentfredric/travis-scripts.git maint-travis-ci
  - time git -C ./maint-travis-ci reset --hard master
  - time perl ./maint-travis-ci/branch_reset.pl
  - time perl ./maint-travis-ci/sterilize_env.pl
before_script:
  - time perl ./maint-travis-ci/before_script.pl
branches:
  only:
    - master
    - build/master
    - releases
install:
  - time perl ./maint-travis-ci/install_deps_early.pl
  - time perl ./maint-travis-ci/install_deps.pl
language: perl
script:
  - time perl ./maint-travis-ci/script.pl
