---
abstract: 'A specific subclass of TravisCI that does horrible things'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::More: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.008, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-Author-KENTNL-TravisCI
provides:
  Dist::Zilla::Plugin::Author::KENTNL::TravisCI:
    file: lib/Dist/Zilla/Plugin/Author/KENTNL/TravisCI.pm
    version: '0.001003'
recommends:
  Moose: '2.000'
  Path::Tiny: '0.058'
requires:
  Dist::Zilla::Plugin::TravisCI: '0.008'
  Moose: '0'
  Path::Tiny: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/kentnl/Dist-Zilla-Plugin-Author-KENTNL-TravisCI/issues
  homepage: https://github.com/kentnl/Dist-Zilla-Plugin-Author-KENTNL-TravisCI
  repository: https://github.com/kentnl/Dist-Zilla-Plugin-Author-KENTNL-TravisCI.git
version: '0.001003'
